#!/bin/bash

MAIN=~/.src/sh/gtd/gtd

GREEN='\033[0;32m'
RED='\033[0;31m'
RESET_COLOR='\033[0m'

if [[ "$OSTYPE" =~ (^darwin|^freebsd) ]]; then
   init=$(date -j +%s)
else
   init=$(date +%s)
fi
pass_cnt=0
fail_cnt=0

assert() {
   if [ "${@:2}" ]; then
      pass_cnt=$(( pass_cnt + 1 ))
      echo -ne "${GREEN}.${RESET_COLOR}"
   else
      fail_cnt=$(( fail_cnt + 1 ))
      echo -ne "${RED}✗${RESET_COLOR}"
      errors="$errors\n$*\n"
   fi
}

echo -e "Running tests...\n"

for file in "$(dirname $MAIN)/tests/"*.test; do
   DEBUG=true source "$file"
done

echo -e "\n${RED}${errors}${RESET_COLOR}"

if [[ "$OSTYPE" =~ (^darwin|^freebsd) ]]; then
   echo -e "Done: $(($(date -j +%s)-init))s. $pass_cnt passed. $fail_cnt failed."
else
   echo -e "Done: $(($(date +%s)-init))s. $pass_cnt passed. $fail_cnt failed."
fi
